@baseUrl=https://localhost:7207
@applicationId=test-app

# @name createAppointmentRequest

POST {{baseUrl}}/Appointment
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "Appointment",
  "status": "proposed",
  "start": "2120-01-03T11:00:00+08:00",
  "end": "2120-01-03T11:30:00+08:00",
  "participant": [
    {
      "actor": {
        "reference": "Patient/testpatient"
      },
      "status": "tentative"
    }
  ]
}


### Get Appointment Request:
@apptId = {{createAppointmentRequest.response.body.$.id}}
# @name getAppointmentRequest
GET {{baseUrl}}/Appointment/1
X-Ihis-SourceApplication: {{applicationId}}

### Update Appointment Request:
# @name updateAppointmentRequest

PUT {{baseUrl}}/Appointment/{{apptId}}
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "Appointment",
  "id": "{{apptId}}",
  "status": "proposed",
  "start": "2120-01-01T12:00:00+08:00",
  "end": "2120-01-01T12:30:00+08:00",
  "description": "For followup",
  "participant": [
    {
      "actor": {
        "reference": "Patient/testpatient"
      },
      "status": "tentative"
    }
  ]
}


### Cancel Appointment Update Request:
# @name cancelAppointmentUpdateRequest

PUT {{baseUrl}}/Appointment/{{apptId}}
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "Appointment",
  "id": "{{apptId}}",
  "status": "cancelled",
  "cancellationReason": {
    "coding": [
      {
        "code": "lost-interest",
        "display": "Lost interest"
      }
    ]
  },
  "start": "2120-01-01T12:00:00+08:00",
  "end": "2120-01-01T12:30:00+08:00",
  "description": "For followup",
  "participant": [
    {
      "actor": {
        "reference": "Patient/testpatient"
      },
      "status": "tentative"
    }
  ]
}

### Cancel Appointment Operation Request:
# @name cancelAppointmentOperationRequest

POST {{baseUrl}}/Appointment/{{apptId}}/$cancel
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "cancellationReason",
      "valueCodeableConcept": {
        "coding": [
          {
            "code": "lost-interest"
          }
        ]
      }
    }
  ]
}


### Move Appointment Operation Request:
# @name moveAppointmentOperationRequest

POST {{baseUrl}}/Appointment/{{apptId}}/$move-appointment-date
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "days-in-future",
      "valueInteger": 5
    }
  ]
}
      
### Search Cancelled Appointment Request:
# @name searchCancelledAppointmentRequest
GET {{baseUrl}}/Appointment?status=cancelled
X-Ihis-SourceApplication: {{applicationId}}
      


### Search by Post Cancelled Appointment Request:
# @name searchCancelledAppointmentRequest
POST {{baseUrl}}/Appointment/_search
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/x-www-form-urlencoded

status=cancelled
