@baseUrl=https://localhost:7207
@applicationId=test-app

GET {{baseUrl}}/Questionnaire/4
X-Ihis-SourceApplication: {{applicationId}}

###
GET {{baseUrl}}/Questionnaire?name=FORM_DS
X-Ihis-SourceApplication: {{applicationId}}
