@baseUrl=https://localhost:7197
@applicationId=test-app

### Metadata Request:

GET {{baseUrl}}/metadata
X-Ihis-SourceApplication: {{applicationId}}
      
### Health Check Request:
GET {{baseUrl}}/health
