@baseUrl=https://localhost:7130
@applicationId=test-app

POST {{baseUrl}}/AcpForm
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "AcpForm",
  "formType": "test",
  "formQuestions": [
    {
      "oID": "1",
      "questionnaireOID": "1",
      "formType": "test",
      "formTypeName": "test",
      "diseaseType": "test",
      "diseaseTypeName": "test"
    }
  ]
}

###
POST {{baseUrl}}/AcpForm
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "AcpForm",
  "formType": "test"
}


###
GET {{baseUrl}}/AcpForm/0E382045539D4A66BB81C9AFC432CFEF
X-Ihis-SourceApplication: {{applicationId}}