@baseUrl=https://localhost:7130
@applicationId=test-app

POST {{baseUrl}}/AcpForm
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "AcpForm",
  "formType": "test",
  "formQuestions": [
    {
      "oID": "1",
      "questionnaireOID": "1",
      "formType": "test",
      "formTypeName": "test",
      "diseaseType": "test",
      "diseaseTypeName": "test"
    }
  ]
}

###
POST {{baseUrl}}/AcpForm
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "AcpForm",
  "formType": "test"
}


###
GET {{baseUrl}}/AcpForm/18082E76-E1F4-455E-9936-D6EC6B6E684A
X-Ihis-SourceApplication: {{applicationId}}

###
GET {{baseUrl}}/AcpForm?formType=FORM_GENERAL
X-Ihis-SourceApplication: {{applicationId}}
