@baseUrl=https://localhost:7130
@applicationId=test-app

POST {{baseUrl}}/AcpFormAnswer
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
	"resourceType": "AcpFormAnswer",
	"oID": "123456789",
	"createdOn": "2022-01-01T00:00:00Z",
	"createdBy": "987654321",
	"createdByName": "John Doe",
	"modifiedOn": "2022-01-02T00:00:00Z",
	"modifiedBy": "123456789",
	"modifiedByName": "Jane Smith",
	"patientOID": "987654321",
	"isHistory": false,
	"version": 1,
	"statusCode": "Active",
	"statusName": "Active",
	"formTypeCode": "ACPF",
	"formTypeName": "ACP Form",
	"placeOfDocumentation": "Hospital",
	"dateOfSession": "2022-01-03T00:00:00Z",
	"programName": "Program A",
	"patientHasSignCode": "Yes",
	"patientHasSignName": "Yes",
	"patientSigningDate": "2022-01-04T00:00:00Z",
	"nHSIdentified": "Yes",
	"isPhysicianHasSigned": "Yes",
	"physicianSignedDate": "2022-01-05T00:00:00Z",
	"facilitatorName": "Alice Johnson",
	"facilitatorNRIC": "S1234567A",
	"facilitatorDesignation": "Facilitator",
	"facilitatorEmail": "alice@example.com",
	"facilitatorSignedDate": "2022-01-06T00:00:00Z",
	"facilitatorInstitution": "Hospital A",
	"livingWellStatement": true,
	"followupPlan": true,
	"uploadedManualForm": false,
	"supportingOthers": true,
	"supportingOthersText": "Supporting others text",
	"aCPContactNumber": "1234567890",
	"physicianName": "Dr. Smith",
	"physicianMCR": "MCR123456",
	"isDeleted": false,
	"createdOrganizationCode": "ORG123",
	"createdOrganizationName": "Organization A",
	"modifiedOrganizationCode": "ORG456",
	"modifiedOrganizationName": "Organization B",
	"publishedDate": "2022-01-07T00:00:00Z",
	"publishedBy": "987654321",
	"publishedByName": "John Doe",
	"publishedOrganizationCode": "ORG789",
	"publishedOrganizationName": "Organization C",
	"facilitatorFullNRIC": "S1234567A",
	"createdOrganizationHCICode": "HCI123",
	"modifiedOrganizationHCICode": "HCI456",
	"publishedOrganizationHCICode": "HCI789",
	"lastModifiedByEmail": "jane@example.com",
	"formAnswers": [
		{
			"oID": "987654321",
			"formOID": "123456789",
			"formQuestionOID": "987654321",
			"questionOptionOID": "123456789",
			"answer": "Answer 1",
			"createdOn": "2022-01-01T00:00:00Z",
			"createdBy": "987654321",
			"createdByName": "John Doe",
			"modifiedOn": "2022-01-02T00:00:00Z",
			"modifiedBy": "123456789",
			"modifiedByName": "Jane Smith"
		}
	]
}

###
POST {{baseUrl}}/AcpFormAnswer
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "AcpForm",
  "formType": "test"
}


###
GET {{baseUrl}}/AcpFormAnswer/0E382045539D4A66BB81C9AFC432CFEF
X-Ihis-SourceApplication: {{applicationId}}